name: "Validate PR pre-merge"

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: ".node-version"
          cache: true
          run-install: true
      - name: Restore Astro cache
        id: astro-cache-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: node_modules/.astro
          key: astro-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            astro-cache-${{ runner.os }}-
      - name: Verify Astro
        run: vp exec astro check && vp run build
      - name: Save Astro cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: node_modules/.astro
          key: ${{ steps.astro-cache-restore.outputs.cache-primary-key }}
